Changed logger to mapped event
mconf/mconf-aggr pull request #30
Opened 2021-07-16 18:39 UTC by GabrielCastroSilva

Added logger to rap-archive-started as a mapped event

2021-07-23 11:36 UTC, akahenry requested changes
The warnings are still occurring.
Probably, the mapped event is used to log information about the received hook and this is generating an exception.
```JSON
{"type":"INFO","time":"Fri Jul 23 11:16:51 2021","code":"Rap-Archive-Started not implemented","site":"map_webhook_event","server":"","event":"","keywords":["webhook", "map", "event", "data structure", "data"],"description":"rap-archive-started event received: 'rap-archive-started'"}
{"type":"WARNING","time":"Fri Jul 23 11:16:51 2021","code":"","site":"AuthMiddleware","server":"","event":"","keywords":null,"description":"Something went wrong: 'NoneType' object has no attribute 'event_type'"}
{"type":"WARNING","time":"Fri Jul 23 11:16:51 2021","code":"","site":"AuthMiddleware","server":"","event":"","keywords":null,"description":"Not publishing event from 'https://fake-live.mconf.com'"}
``` 

Take a look at:
https://github.com/mconf/mconf-aggr/blob/ad3dde84c897c99e7b0870ad9bbf5d9c042c86f4/mconf_aggr/webhook/event_listener.py#L323
This line fits the warning message and is likely causing the error. Removing it should fix this exception.
Don't forget to add this line on another site when the app starts logging the `Publishing webhook event` on line 332.

2021-07-23 18:20 UTC, GabrielCastroSilva commented
> The warnings are still occurring.
> Probably, the mapped event is used to log information about the received hook and this is generating an exception.
> 
> ```json
> {"type":"INFO","time":"Fri Jul 23 11:16:51 2021","code":"Rap-Archive-Started not implemented","site":"map_webhook_event","server":"","event":"","keywords":["webhook", "map", "event", "data structure", "data"],"description":"rap-archive-started event received: 'rap-archive-started'"}
> {"type":"WARNING","time":"Fri Jul 23 11:16:51 2021","code":"","site":"AuthMiddleware","server":"","event":"","keywords":null,"description":"Something went wrong: 'NoneType' object has no attribute 'event_type'"}
> {"type":"WARNING","time":"Fri Jul 23 11:16:51 2021","code":"","site":"AuthMiddleware","server":"","event":"","keywords":null,"description":"Not publishing event from 'https://fake-live.mconf.com'"}
> ```
> 
> Take a look at:
> 
> https://github.com/mconf/mconf-aggr/blob/ad3dde84c897c99e7b0870ad9bbf5d9c042c86f4/mconf_aggr/webhook/event_listener.py#L323
> 
> This line fits the warning message and is likely causing the error. Removing it should fix this exception.
> Don't forget to add this line on another site when the app starts logging the `Publishing webhook event` on line 332.

Added recommended changes, should all be resolved now. If there's anything else let me know.

2021-07-23 19:01 UTC, akahenry commented
The second warning is still hapenning. 
You can create a deprecated events list or another structure to log only when these not deprecated events are being handled.

2021-07-23 19:02 UTC, akahenry requested changes
The second warning is still hapenning.
You can create a deprecated events list or another structure to log only when these not deprecated events are being handled.

2021-07-28 14:53 UTC, leninribeiro approved these changes
The application now logs 

> mconf-aggr-webhook_1  | {"type":"INFO","time":"Wed Jul 28 14:50:09 2021","code":"Rap-Archive-Started not implemented","site":"map_webhook_event","server":"","event":"","keywords":["webhook", "map", "event", "data structure", "data"],"description":"rap-archive-started event received: 'rap-archive-started'"}
mconf-aggr-webhook_1  | {"type":"DEBUG","time":"Wed Jul 28 14:50:09 2021","code":"Not implemented","site":"WebhookEventHandler.process_event","server":"https://fake-live.mconf.com","event":"","keywords":["WebhookEventHandler", "parse", "publish", "data", "process", "to aggregator"],"description":"Event deprecated."}

when receiving rap-archive-started

2021-08-02 12:50 UTC, akahenry requested changes

2021-08-02 12:50 UTC, akahenry commented on mconf_aggr/aggregator/cfg.py
> +        self._config["MCONF_WEBHOOK_DEPRECATED_EVENTS"] = os.getenv("MCONF_WEBHOOK_DEPRECATED_EVENTS").split(",")
There are two problems with your solution:
- There is no default value. If this variable is not set, it will throw an exception;
- If the variable has an empty string, the deprecated events will not be empty because you are splitting using the `,` character.

Instead of splitting using `,` character, replace the `,` character to spaces and then split with spaces.
```
os.getenv("MCONF_WEBHOOK_DEPRECATED_EVENTS", "").replace(",", " ").split()
```

2021-08-02 12:50 UTC, akahenry commented on mconf_aggr/webhook/event_listener.py
> +                        self.logger.debug("Event deprecated.", extra=dict(logging_extra, keywords=json.dumps(logging_extra["keywords"])))
This log should be an INFO and it should be more expressive (something like `Event deprecated` in `code` field and a description showing the deprecated events list). 

Also, you can set the `event` key and `server` key in `logging_extra` because you have them at this point.

2021-08-02 12:50 UTC, akahenry commented on mconf_aggr/webhook/event_mapper.py
> +    logger.info("rap-archive-started event received: '{}'".format(event_type), extra=dict(logging_extra, keywords=json.dumps(logging_extra["keywords"])))
It doesn't make sense to log explicitly the event name and format the log with the `event_type` (which is the event name). 

As you have created a list of deprecated events and is already logging it in `event_listener`, you doesn't need to log it here too. Then, you should only parse the event and return it.
To parse this event, you can add `rap-archive-started` to be mapped as a default rap-event (line 224) and remove this function and the old mapping (line 237).

2021-08-02 12:50 UTC, akahenry commented on mconf_aggr/webhook/event_listener.py
> +                    if webhook_event.event in deprecated_events:
You should use the `event_type` attribute and not the `event`.

2021-08-09 22:25 UTC, akahenry approved these changes

2021-08-09 22:25 UTC, merged